m1=int(input("enter marks of student number 1: "))
m2=int(input("enter marks of student number 2: "))
m3=int(input("enter marks of student number 3: "))
m4=int(input("enter marks of student number 4: "))
m5=int(input("enter marks of student number 5: "))
m6=int(input("enter marks of student number 6: "))
m7=int(input("enter marks of student number 7: "))
mylist=[m1,m2,m3,m4,m5,m6,m7]
mylist.sort()
print(mylist)
